#                                                      Codility Test

### Q1. Find the alphabet that appears for the maximum number of times in a given string, if two alphabet occours for the same number of times return the one that occurs first alphabetically, between 'c' and 'e' return c.

In [1]:
def solution(S):
    occurrences = [0] * 26

    for i in range(len(S)):
        occurrences[ord(S[i]) - ord('a')] += 1
        print(occurrences)
    best_char = 'a'
    best_res = 0

    for i in range(0, 25):
        if occurrences[i] > best_res:
            best_char = chr(ord('a') + i)
            best_res = occurrences[i]
            print(best_char,occurrences[i])
    return best_char
solution('abcdefghijklmnopqrstuvwxyz')
solution("hello")

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 

'l'

### Q2. Define a function such that if we pass names of employee's separated by ; as a string along with company name it returns email address's as in example below, if two people have same email address make them distinct as x_y_z@example.com and x_y_z2@example.com.

#### String Passed= "John Doe; Peter Benjamin Parker; Mary Jane Watson-Parker; John Elvis Doe; John Evan Doe; Jane Doe; Peter Brian Parker"

#### Output Returned= "john_doe@example.com; peter_b_parker@example.com; mary_j_watsonparker@example.com; john_e_doe@example.com; john_e_doe2@example.com; jane_doe@example.com; peter_b_parker2@example.com"

In [2]:
# you can write to stdout for debugging purposes, e.g.
# print("this is a debug message")

def solution(S,C):
    
    x=S.count(';')
    y=x+1
    #c="example"
    
    firstname  = [0] * y
    middlename = [0] * y
    lastname   = [0] * y
    email      = [0] * y
    
    list = S.split(";")
    
    for i in range(0, y):
        firstname[i] = ''
        firstname[i] = list[i].split()[0]
        middlename[i] = ''
        middlename[i] = list[i].split()[1] 
        length = len(list[i].split())
        if length == 3:
            lastname[i]= list[i].split()[2]
            middlename[i] = middlename[i][0]
        else:
            lastname[i]=''
        firstname[i]  = firstname[i].replace("-", "").lower()
        middlename[i] = middlename[i].replace("-", "").lower()
        lastname[i]   = lastname[i].replace("-", "").lower()
        if length == 3:
            email[i] =  firstname[i]+"_"+middlename[i]+"_"+lastname[i]+"@"+C.lower()+".com"
        else:
            email[i] = firstname[i]+"_"+middlename[i]+"@"+C.lower()+".com"
        
    RS = ""
    for i in range(0, y):
        cn=0
        for j in range(0, y):
            if email[j] ==  email[i] and i != j:
                cn+=1
                email[j] = firstname[j]+"_"+middlename[j]+"_"+lastname[j]+str(cn+1)+"@"+C.lower()+".com"
        RS += email[i]+"; "
    RS=RS[:-2] 
    
    return RS 
   

        
    pass


solution("John Doe; Peter Benjamin Parker; Mary Jane Watson-Parker; John Elvis Doe; John Evan Doe; Jane Doe; Peter Brian Parker","Example")

'john_doe@example.com; peter_b_parker@example.com; mary_j_watsonparker@example.com; john_e_doe@example.com; john_e_doe2@example.com; jane_doe@example.com; peter_b_parker2@example.com'

### Q3. Define a function that returns the Day after a specific number of days from days.
###        'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'
#### Day="Wed" after_days = 2, Returns "Fri"
#### Day=Sat"  after_days = 23, Return "Mon"

In [3]:
def solution(S, K):
    Day = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    rem=K%7
    for i in range (0, 7):
        if S == Day[i]:
            cnt = i + rem
            if cnt > 6:
                cnt = cnt%7
            else:
                cnt=cnt
    return Day[cnt]
            
            
    # write your code in Python 3.6
    pass
solution("Sat",23)

'Mon'

### Q4. Define a function to find square root between two numbers.

#### for A=10, B=20, max_square_roots number is 16, i.e. 16 to 4 to 2 i.e returns 2 as total square roots

#### for A=6000, B=7000, max_square_roots number is 6561, i.e 6561 to 81 to 9 to 3 as total square roots

In [4]:
def solution(A, B):
    import math
    max=0
    for i in range(A,B):
        cnt=0
        x = math.sqrt(i)   
        y=int(x)
        if x==y:
            cnt+=1
            #print(y,cnt)
            while True:
                z=math.sqrt(y)
                q=int(z)
                if q==z:
                    cnt+=1
                y=q
                if(y>1 and y<9):
                    break
        if max<cnt:
            max=cnt
    return max
    # write your code in Python 3.6
    pass

#solution(10,20)
solution(6000,7000)

3

### Q5. Define a function to generate random numbers such that the sum of all random numbers equal to 0.

#### for input N =4 generate numbers like [[-10  -3   4   9]]

In [5]:
def solution(N):
    import numpy as np
    arr = np.random.randint(-10, 10, (100, N))
    arr1=(arr[arr.sum(1) == 0])
    return print(arr1)
    
    # write your code in Python 3.6
    pass
solution(4)

[[ 2 -8  6  0]
 [-5  9 -2 -2]
 [ 0 -8  1  7]]
